In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
import seaborn as sns
sns.set()

In [5]:
from scipy import optimize

In [6]:
from ipywidgets import *

In [7]:
from IPython.display import SVG

In [8]:
from sklearn import datasets

In [9]:
AND = pd.DataFrame({ 'x1':(0,0,1,1) ,
                     'x2':(0,1,0,1),
                     'y':(0,0,0,1)})

In [24]:
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [11]:
w  = np.random.randn(3)*1e-4

In [25]:
w

array([-0.3, -0.3,  0.3])

In [26]:
g = lambda inputs , weights: np.where(np.dot(inputs,weights)>0,1,0)

#If dot product is greater than 0 print 1 otherwise print 0 

In [27]:
inputs = AND[['x1','x2']]
inputs

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [28]:
-np.ones((len(inputs),1))   #Biases   
                            # we can use other numbers also other than -1

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [29]:
a = np.c_[inputs , -np.ones((len(inputs),1))]
a

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [17]:
w

array([-0.00013263,  0.0001023 ,  0.00012012])

In [30]:
np.dot(a,w)  #Dot product a = 4 x 3
                        # w = 3 x 1
                    # a x w = 4 x 1

array([-0.3, -0.6, -0.6, -0.9])

In [36]:
def train(inputs , targets , weights , eta ,n_iterations):
    inputs = np.c_[inputs , -np.ones((len(inputs),1))]
    
    for n in range(n_iterations):
        activations = g(inputs , weights);
        print(n,activations)
        weights = eta*np.dot(np.transpose(inputs),activations - targets)
        print(n,weights)
 
        
    return(weights)

In [37]:
inputs = AND[['x1','x2']]
targets = AND['y']
 
w = train(inputs,targets , w,.3 ,10)     #Learning rate = 10

0 [0 0 0 0]
0 [-0.3 -0.3  0.3]
1 [0 0 0 0]
1 [-0.3 -0.3  0.3]
2 [0 0 0 0]
2 [-0.3 -0.3  0.3]
3 [0 0 0 0]
3 [-0.3 -0.3  0.3]
4 [0 0 0 0]
4 [-0.3 -0.3  0.3]
5 [0 0 0 0]
5 [-0.3 -0.3  0.3]
6 [0 0 0 0]
6 [-0.3 -0.3  0.3]
7 [0 0 0 0]
7 [-0.3 -0.3  0.3]
8 [0 0 0 0]
8 [-0.3 -0.3  0.3]
9 [0 0 0 0]
9 [-0.3 -0.3  0.3]


In [33]:
# print(activation,weights)


In [34]:
w

array([-0.3, -0.3,  0.3])

In [35]:
g(np.c_[inputs , -np.ones((len(inputs),1))],w)  

array([0, 0, 0, 0])

In [221]:
OR  = pd.DataFrame({ 'x1':(0,0,1,1) ,
                     'x2':(0,1,0,1),
                     'y':(0,1,1,1)})
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [222]:
w  = np.random.randn(3)*1e-4
w

array([ 1.27444979e-04, -1.56373609e-05, -9.52925470e-05])

In [223]:
g = lambda inputs , weights: np.where(np.dot(inputs,weights)>0,1,0)

#If dot product is greater than 0 print 1 otherwise print 0 

In [224]:
inputs = AND[['x1','x2']]
inputs

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [225]:
-np.ones((len(inputs),1))   #Biases   
                            # we can use other numbers also other than -1

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [226]:
a = np.c_[inputs , -np.ones((len(inputs),1))]
a

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [227]:
w

array([ 1.27444979e-04, -1.56373609e-05, -9.52925470e-05])

In [228]:
np.dot(a,w)  #Dot product a = 4 x 3
                        # w = 3 x 1
                    # a x w = 4 x 1

array([9.52925470e-05, 7.96551861e-05, 2.22737526e-04, 2.07100165e-04])

In [229]:
def train(inputs , targets , weights , eta ,n_iterations):
    inputs = np.c_[inputs , -np.ones((len(inputs),1))]
    
    for n in range(n_iterations):
        activations = g(inputs , weights);
        print(n,activations)
        weights = eta*np.dot(np.transpose(inputs),activations - targets)
        print(n,weights)
 
        
    return(weights)

In [230]:
inputs = OR[['x1','x2']]
targets = OR['y']
 
w = train(inputs,targets , w,0.001 ,20)     #Learning rate = 20
                                         #iterions = 10

0 [1 1 1 1]
0 [ 0.     0.    -0.001]
1 [1 1 1 1]
1 [ 0.     0.    -0.001]
2 [1 1 1 1]
2 [ 0.     0.    -0.001]
3 [1 1 1 1]
3 [ 0.     0.    -0.001]
4 [1 1 1 1]
4 [ 0.     0.    -0.001]
5 [1 1 1 1]
5 [ 0.     0.    -0.001]
6 [1 1 1 1]
6 [ 0.     0.    -0.001]
7 [1 1 1 1]
7 [ 0.     0.    -0.001]
8 [1 1 1 1]
8 [ 0.     0.    -0.001]
9 [1 1 1 1]
9 [ 0.     0.    -0.001]
10 [1 1 1 1]
10 [ 0.     0.    -0.001]
11 [1 1 1 1]
11 [ 0.     0.    -0.001]
12 [1 1 1 1]
12 [ 0.     0.    -0.001]
13 [1 1 1 1]
13 [ 0.     0.    -0.001]
14 [1 1 1 1]
14 [ 0.     0.    -0.001]
15 [1 1 1 1]
15 [ 0.     0.    -0.001]
16 [1 1 1 1]
16 [ 0.     0.    -0.001]
17 [1 1 1 1]
17 [ 0.     0.    -0.001]
18 [1 1 1 1]
18 [ 0.     0.    -0.001]
19 [1 1 1 1]
19 [ 0.     0.    -0.001]


In [231]:
w

array([ 0.   ,  0.   , -0.001])

In [204]:
g(np.c_[inputs , -np.ones((len(inputs),1))],w)  

array([1, 1, 1, 1])